#!/bin/bash

clear

echo ========== Setup
make clean

echo -e "\n========== Should compile everything and link"
make

echo -e "\n========== Should recompile everything and link"
touch include/functions.hpp
make

echo -e "\n========== Should recompile main only and link"
touch source/main.cpp
make

echo -e "\n========== Teardown"
make clean
