#!/bin/bash

clear

echo ========== Setup
make clean
make

echo -e "\n========== Should recompile functions.cpp and main.cpp"
touch include/functions.h
make

echo -e "\n========== Teardown"
make clean
